export default {
  container: {
    position: 'fixed' as const,
    zIndex: 99,
    height: '100%',
    width: '100%',
    display: 'flex',
    alignItems: 'flex-start',
    justifyContent: 'center',
    backgroundColor: 'rgba(0,0,0,0.5)',
  },
  modal: {
    position: 'absolute' as const,
    flexDirection: 'column' as const,
    height: 400,
    width: '95%',
    maxWidth: 400,
    backgroundColor: '#000',
    opacity: 1,
    top: 80,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#3817B8',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    overflow: 'hidden',
    transition: 'transform 0.3s ease-in-out',
    transform: 'translateY(-10px)',
    boxShadow: '0px 0px 7px 2px #3817B8',
  },
}
